#!/usr/local/bin/python

####################################################################################
##                                                                                ##
##                             500px PROMOTION SCRIPT                             ##
##                 It's my first script on Python, so if you have                 ##
##          some questions or suggestion write me to forthgate@gmail.com          ##
##                                                                                ##
####################################################################################

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
import time
from pyvirtualdisplay import Display
import getpass

display = Display(visible=0, size=(800, 600))
display.start()
chrome_options = Options()
driver = webdriver.Chrome('./chromedriver')
driver.get('https://500px.com/login')
login = driver.find_element_by_xpath('//*[@id="email"]')
x=raw_input('Login: ')
y=getpass.getpass()
login.send_keys(x)
time.sleep(5)
password = driver.find_element_by_xpath('//*[@id="password"]')
password.send_keys(y)
time.sleep(1)
password.send_keys(Keys.RETURN)
time.sleep(5)
driver.get('https://500px.com/fresh')

time.sleep(5)
driver.find_element_by_xpath('//*[@id="content"]/div/div[1]/div[3]/div/div[1]/div/div/div[1]/a').click() #select first photo in fresh
time.sleep(5)
driver.find_element_by_xpath('//*[@id="modal_content"]/div/div[2]/div[3]/div/div[4]/div/div[1]/div[1]/div/a').click() #click like button first time
time.sleep( 7 )
all=0
while True:
	i=0
	while i <20:
		driver.find_element_by_xpath('//*[@id="modal_content"]/div/div[2]/div[3]/div/div[4]/div/div[1]/div[1]/div/a').click() #click like button second time
		time.sleep(3)
		driver.find_element_by_xpath('//*[@id="modal_content"]/div/div[2]/div[1]/div[1]/div[5]/div').click() # go to next photo
		time.sleep(1)
		i=i+1
		all=all+1
		print (all)
	else:
		driver.get('https://500px.com/fresh')
		time.sleep(5)
		driver.find_element_by_xpath('//*[@id="content"]/div/div[1]/div[3]/div/div[1]/div/div/div[1]/a').click() #select first photo in fresh again
		time.sleep ( 2 )
		driver.find_element_by_xpath('//*[@id="modal_content"]/div/div[2]/div[3]/div/div[4]/div/div[1]/div[1]/div/a').click() #click like button first time
		time.sleep( 7 )
		i=0
