#! /bin/bash
# byobu - alternative tmux or screen
# needrestart - show which services must restart after updates
# chrony - ntp client; ncdu - Text-based disk usage viewer
i="mc htop git curl sudo unzip nmap byobu vim net-tools chrony needrestart ncdu"
release=$(cat /etc/*release | awk 'NR==2' | grep -io debian)
if  [[ $release = Debian ]]; then
    apt-get update && apt-get install -y  $i
    for z in $i; do
        if dpkg-query -l $z | awk {'print $2'} | grep $z 1>/dev/null; then
            echo -e  " $z \e[32mInstalled \e[39m"
        else
            echo -e  " $z \e[31mNot Installed \e[39m"
        fi
    done
fi

# Set server address in zabbix-agent.conf

echo " Configuring zabbix-agent... "
sed -i 's#Server=127.0.0.1#Server=172.26.133.190#g' $ZABCONF
service zabbix-agent restart

#Check zabbix-agent status

if [[ $( service zabbix-agent status | grep  "Active: active" ) == "Active: active" ]]; then
   echo "Succesfull!"
else
   echo " \e[31mError! \e[39m "
fi
